modLoader="javafml" #mandatory
loaderVersion="[2,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Paxi/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG"
    description="${mod_description}"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/paxi-neoforge"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${mc_version},1.21)"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-NeoForge-${yungsapi_version},)"
    type="required"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "paxi.mixins.json"

[[mixins]]
    config = "paxi_neoforge.mixins.json"